name: geminabox

image:
  repository: quay.io/reevoo/geminabox

env:
  APP_NAME:
    doc: name of the app
    value: geminabox

app:
  replicas: 1
  strategy:
    type: Recreate
  workload: general
  command: ["/app/server/entrypoint.sh"]
  port: 9292
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 30
    timeoutSeconds: 20
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    timeoutSeconds: 20
  resources:
    requests:
      memory: 512Mi
      cpu: 250m
    limits:
      memory: 1028Mi
      cpu: 750m
  volumes:
    storage-efs: /app/geminabox/data

