name: geminabox

image:
  repository: quay.io/reevoo/geminabox

env:
  RAILS_ENV:
    value: production
  RACK_ENV:
    value: production
  APP_NAME:
    doc: name of the app
    value: geminabox

app:
  replicas: 1
  workload: general
  command: ["/app/server/entrypoint.sh"]
  port: 9292
  livenessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
    timeoutSeconds: 10
  readinessProbe:
    httpGet:
      path: /
      port: http
    initialDelaySeconds: 10
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 150m

persistentVolume:
  geminabox:
    efsEndpoint: fs-9fe62f57.efs.eu-west-1.amazonaws.com
    mountpoint: /app/geminabox/data

ingress:
  access: internal
  host: gems.reevoocloud.com
