apiVersion: apps/v1
kind: Deployment
metadata:
  name: geminabox
  labels:
    app: geminabox
    chart: reevooapp-0.1.0
    release: RELEASE-NAME
    heritage: Tiller
    app.kubernetes.io/name: geminabox
    helm.sh/chart: reevooapp-0.1.0
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/version: 1.0.0
    app.kubernetes.io/component: geminabox

spec:
  selector:
    matchLabels:
      app: geminabox
      chart: reevooapp-0.1.0
      release: RELEASE-NAME
      heritage: Tiller
      app.kubernetes.io/name: geminabox
      helm.sh/chart: reevooapp-0.1.0
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/instance: RELEASE-NAME
      app.kubernetes.io/version: 1.0.0
      app.kubernetes.io/component: geminabox

      failure-domain.beta.kubernetes.io/zone: eu-west-1a

  replicas: 1
  template:
    metadata:
      labels:
        app: geminabox
        chart: reevooapp-0.1.0
        release: RELEASE-NAME
        heritage: Tiller
        app.kubernetes.io/name: geminabox
        helm.sh/chart: reevooapp-0.1.0
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: RELEASE-NAME
        app.kubernetes.io/version: 1.0.0
        app.kubernetes.io/component: geminabox

      annotations:
        checksum/env: 52a3834189691190e9c0ce8d1501dfdf669366c3311a9272392502f7185226cd
    spec:
      containers:
        - name: geminabox
          image: "quay.io/reevoo/geminabox:7473667e64989357adae871ede5ba3dc8b547edf"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9292
          command: ["/app/server/entrypoint.sh"]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: STATSD_URL
              value: udp://$(NODE_IP):8125
            - name: DATADOG_TRACE_AGENT_HOSTNAME
              value: $(NODE_IP)
            - name: DATADOG_TRACE_AGENT_PORT
              value: "8126"

          volumeMounts:
            - name: geminabox-pv
              mountPath: /app/geminabox/data
          envFrom:
            - configMapRef:
                name: RELEASE-NAME-env
            - secretRef:
                name: RELEASE-NAME-env
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            timeoutSeconds: 20

          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10

          resources:
            limits:
              cpu: 1500m
              memory: 768Mi
            requests:
              cpu: 1500m
              memory: 768Mi

      dnsPolicy: ClusterFirst
      nodeSelector:
        environment: default
        workload: general
      imagePullSecrets:
        - name: reevoo-conan-pull-secret
      initContainers:
        - name: volume-mount-perm
          image: busybox
          command: ["sh", "-c", "chmod 1777 /app/geminabox/data"]
          volumeMounts:
            - name: geminabox-pv
              mountPath: /app/geminabox/data

      volumes:
        - name: geminabox-pv
          persistentVolumeClaim:
            claimName: geminabox-default-pvc

