version: '3.4'
services:

  app:
    build:
      context: .
    ports:
      - 9292:9292
    environment:
      RAILS_ENV: test
      RACK_ENV: test
    volumes:
      - .:/app
    command: ["bundle", "exec", "puma", "-C", "/webapps/server/config/config.ru"]
