steps:

  - label: ":docker: Build"
    command: |
      make publish

  - wait

  # - block: ":rocket: Deploy to staging! :dragon:"

  # - label: ":helm: :arrow_right: :k8s: staging"
  #   command: make deploy
  #   plugins:
  #     - ssh://git@github.com/reevoo/konfiguration-buildkite-plugin.git#v0.0.2: ~
  #     - ssh://git@github.com/reevoo/git-buildkite-plugin.git#v0.0.3:
  #         repo: git@github.com:reevoo/charts.git
  #         branch: v2.0
  #         dest: charts
  #     - docker#v2.0.0:
  #         image: "quay.io/reevoo/kube-release:eks"
  #         workdir: "/app"
  #         volumes:
  #           - ".:/app"
  #         environment:
  #           - "K8S_CLUSTER"
  #           - "K8S_NAMESPACE"
  #           - "BUILDKITE_COMMIT"
  #   env:
  #     K8S_CLUSTER: zeus
  #     K8S_NAMESPACE: staging

  - block: ":rocket: Deploy to production! :dragon:"
    fields:
      - select: "I'm sure, I'm deploying to PRODUCTION!"
        key: "unleash-the-dragon"
        options:
          - label: ":dragon_face: yes, unleash the dragon! :dragon:"
            value: "yes"

  - label: ":helm: :arrow_right: :k8s: production"
    command: make deploy
    plugins:
      - ssh://git@github.com/reevoo/konfiguration-buildkite-plugin.git#v0.0.2: ~
      - ssh://git@github.com/reevoo/git-buildkite-plugin.git#v0.0.3:
          repo: git@github.com:reevoo/charts.git
          branch: v3.1.3
          dest: charts
      - docker#v2.0.0:
          image: "quay.io/reevoo/kube-release:eks"
          workdir: "/app"
          volumes:
            - ".:/app"
          environment:
            - "K8S_CLUSTER"
            - "K8S_NAMESPACE"
            - "BUILDKITE_COMMIT"
    env:
      K8S_CLUSTER: zeus
      K8S_NAMESPACE: production
