env:
  RAILS_ENV:
    value: production
  RACK_ENV:
    value: production

ingress:
  access: internal
  host: gems.reevoocloud.com
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 16m

volumes:
  - type: ebs
    name: geminabox-storage
    mountPath: /app/geminabox/data
    ebsVolumeID: vol-0b0e6b807e15025dc
    ebsVolumeAZ: eu-west-1a

